"""Export utilities — converts puzzle data to JSON or JavaScript output."""

import json
from typing import Optional

from models import Puzzle
from difficulty import rate_difficulty

PALETTE = [
    "#bfdbfe", "#d9f99d", "#fbcfe8", "#fde68a",
    "#a5f3fc", "#fca5a5", "#c4b5fd", "#86efac",
]


def export_puzzle_json(
    puzzle: Puzzle,
    sol: list,
    puzzle_id: str,
    colors: Optional[list] = None,
) -> str:
    """
    Serialise a puzzle as JSON for the front-end, including difficulty metadata.

    The output includes a `meta` block with twoByTwoCount, branchesNeeded,
    and difficulty label so the front-end can select puzzles by difficulty.
    """
    meta = rate_difficulty(puzzle, sol)

    regions = [
        {
            "id":    cl.id,
            "clueR": cl.clue_r,
            "clueC": cl.clue_c,
            "area":  cl.area,
            "perim": cl.perim,
            "color": (colors[i] if colors and i < len(colors) else PALETTE[i % len(PALETTE)]),
        }
        for i, cl in enumerate(puzzle.clues)
    ]

    data = {
        "id":       puzzle_id,
        "rows":     puzzle.rows,
        "cols":     puzzle.cols,
        "solution": sol,
        "regions":  regions,
        "meta":     meta,
    }
    return json.dumps(data, indent=2)


def export_js(puzzle: Puzzle, sol: list) -> str:
    """Emit the puzzle as JavaScript arrays (legacy helper for manual copy-paste)."""
    rows, cols = puzzle.rows, puzzle.cols
    lines = [
        f"// {rows}×{cols} puzzle — generated by solver",
        "",
        "const SOL = [",
    ]
    for r in range(rows):
        lines.append(f"  [{', '.join(str(sol[r][c]) for c in range(cols))}],")
    lines += ["];", "", "const REGIONS = ["]
    for cl in puzzle.clues:
        lines.append(
            f"  {{id:{cl.id}, clueR:{cl.clue_r}, clueC:{cl.clue_c}, "
            f"area:{cl.area}, perim:{cl.perim}}},"
        )
    lines.append("];")
    return "\n".join(lines)
